version: '3.7'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: data
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
  mysql:
     image: mysql:8.0
     ports:
       - '3306:3306'
     volumes:
           - ./data:/var/lib/postgresql/data
     environment:
       - MYSQL_RANDOM_ROOT_PASSWORD=yes
       - MYSQL_DATABASE=data
       - MYSQL_USER=app
       - MYSQL_PASSWORD=pass